// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"user.service/internal/biz/logic"
	"user.service/internal/data/mysql"
	"user.service/pkg/conf"
	"user.service/pkg/database"
)

// Injectors from wire.go:

func initLogic() (*logic.UserLogic, error) {
	myConfig, err := conf.Init()
	if err != nil {
		return nil, err
	}
	db, err := database.InitMySQL(myConfig)
	if err != nil {
		return nil, err
	}
	userRepo := &mysql.UserRepo{
		DB: db,
	}
	userLogic := &logic.UserLogic{
		UserRepo: userRepo,
	}
	return userLogic, nil
}
